### DISCUSSION TITLE
Index Lookup Configuration

### DISCUSSION THREAD

**Discussion by JimPiquant** [microsoft/promptflow#3096] [Q&A]
I'm using the Index Lookup tool in a flow in VS code.  It works, but it is using the ML workspace connection for AI Search.  Can I configure this to use my local connection?  I can't find any syntax examples.  Here is the current setup:

```
        connection:
          id: 
            /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-xxxx/providers/Microsoft.MachineLearningServices/workspaces/promptflows/connections/open_ai_connection
        connection_type: workspace_connection
```
Thanks!
