### DISCUSSION TITLE
How to fix the issue where the prompt flow node is always trying to create an input image?

### DISCUSSION THREAD

**Discussion by l0ginp** [microsoft/promptflow#3633] [Q&A]
I write loop to generate dynamic content, but when I include inside the loop, it is always considered as new input type image.

Is there a way to fix it, or what should I do?
 
<img width="559" alt="Screenshot 2567-08-08 at 15 07 00" src="https://github.com/user-attachments/assets/8dab5cf7-a4ab-44f7-ad36-f249000625c8">

**Comment by brynn-code** [comment]
Hi, I just read the related part of the inputs resolving, it looks like we will regard the `![image]({{}})` as image input type, to input as plain string, maybe you could write template parameter as `{{item}}` and make each item started with `![image]...`

**Comment by l0ginp** [comment]
If I have more than one picture, do I have to do it one by one like this? Is that correct?

```yaml
![image]({{img1}})
![image]({{img2}})
![image]({{img3}})
```


and input will be ?
```yaml
input:
    image1: ${image_data.image_1}
    image2: ${image_data.image_2}
    image3: ${image_data.image_3}
```
