### DISCUSSION TITLE
In PromptFlow, is there a way to include multiple conditions in the activate config?

### DISCUSSION THREAD

**Discussion by l0ginp** [microsoft/promptflow#3715] [Q&A]
This my current config code

```yml
- name: node1
  type: python
  source:
    type: code
    path: node2.py
  inputs:
    chat_msg_list: ${node1.output.text_msg}
  activate:
    when: ${node1.output.category_code}
    is: P2
```

expect
```yml
  activate:
    when: ${node1.output.category_code}
    is: P3 or P4 or P5
```
