### DISCUSSION TITLE
promptflow_vectordb tool search: using api key to connect to azure AI search

### DISCUSSION THREAD

**Discussion by teebu** [microsoft/promptflow#3833] [Q&A]
The tool im using is using the `connection_type: workspace_connection` with full workspace subscription path. I want to use API Keys from my connection strings and not have to rely on being logged in (az login) locally for this to run. I need help or a sample config on how to create a mlindex_content that uses local pf connection I set instead.

https://learn.microsoft.com/en-us/azure/ai-studio/how-to/prompt-flow-tools/index-lookup-tool#inputs

Sample from my `flow.dag.yaml`
```
  - name: querySearchResource
    type: python
    source:
      type: package
      tool: promptflow_vectordb.tool.common_index_lookup.search
    inputs:
      mlindex_content: >
        embeddings:
          api_base: https://<base>.openai.azure.com/
          api_type: azure
          api_version: 2023-07-01-preview
          batch_size: '1'
          connection:
            id: /subscriptions/someid/resourceGroups/somerg/providers/Microsoft.MachineLearningServices/workspaces/someworkspace/connections/someconnection
          connection_type: workspace_connection
          deployment: text-embedding-ada-002
          dimension: 1536
          kind: open_ai
          model: text-embedding-ada-002
          schema_version: '2'
        index:
          api_version: 2024-05-01-preview
          connection:
            id: /subscriptions/someid/resourceGroups/somerg/providers/Microsoft.MachineLearningServices/workspaces/someworkspace/connections/AzureAISearch
          connection_type: workspace_connection
          endpoint: https://<base>.search.windows.net
          engine: azure-sdk
          field_mapping:
            content: content
            embedding: contentVector
            metadata: meta_json_string
          index: testindex
          kind: acs
          semantic_configuration_name: azureml-default
      queries: ${extractSearchIntent.output}
      query_type: Hybrid + semantic
      top_k: 20
    use_variants: false
```
