### ISSUE TITLE
[Feature Request] Manipulate data before LLM input

### ISSUE THREAD

**Issue by simon-v-swyftx** [microsoft/promptflow#1074]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I've got a webhook from a third party that I can't modify the shape of before it hits my promptflow endpoint.
Is there a way that I can first modify/massage the data coming in before the "Inputs" step of the flow?

**Describe alternatives you've considered**
The payload has a lot of top level key values, so can just manually add each of them to the Inputs, just looks pretty messy.

**Additional context**

**Comment by wangchao1230** [comment]
Thanks for the feedback! 

Could you describe more on what's the webhook here? 
Do you mean it has a big dict with many keys and you need to pass the it as many inputs to a flow?

Is it appliable that you change the flow input to accept a dict? You can add a node parsing the dict inside the flow.
@simon-v-swyftx

**Comment by simon-v-swyftx** [comment]
>Do you mean it has a big dict with many keys and you need to pass the it as many inputs to a flow?
Yep that's exactly right!

It's almost as if I want a python tool before the "Inputs" step.
So rather than having something like this:
![image](https://github.com/microsoft/promptflow/assets/109499378/7770b9a1-0b65-4224-af1a-4b010558cbbc)

I now need to add my big dict manually (and this gets a little annoying as I have two different webhooks, with slightly different shape hitting this endpoint)
![image](https://github.com/microsoft/promptflow/assets/109499378/4b86665d-281e-4d7b-ba58-6be57593292e)

Of course I could spin up another endpoint to act as a middleware, but I'd much prefer to handle it all in the promptflow
@wangchao1230

**Comment by wangchao1230** [comment]
Could you create a flow with a object input webhook, and add preprocess python node in the flow before the llm node to process that input?
Is there any blocker you met with this way?

**Comment by simon-v-swyftx** [comment]
I believe the problem is that the input section assumes a property called 'webhook' in this example.

Assume the payload looks like this *which I cannot change*

```json
{
    "property1": "hello",
    "property2": "test",
    "property3": "world",
    "property4": "texthere",
    ...many many more properties that could be nested
}
```

with the following flow:
```yaml
id: use_functions_with_chat_models
name: Use Functions with Chat Models
environment:
  python_requirements_txt: requirements.txt
inputs:
  webhook:
    type: object
    default: {}
outputs:
  answer:
    type: string
    reference: ${ingest_webhook.output}
    is_chat_output: true
nodes:
- name: ingest_webhook
  type: python
  source:
    type: code
    path: ingest_webhook.py
  inputs:
    connection: Intercom
    webhook: ${inputs.webhook}
  use_variants: false
```

where `injest_webhook.py` looks like:

```python
from promptflow import tool
from promptflow.connections import CustomConnection


@tool
def injest_webhook(connection: CustomConnection, webhook: object = None) -> str:
    return str(webhook)
```

The above will error, because I haven't defined all the properties.

but the below will work:

```json
{
    "webhook": {
        "property1": "hello",
        "property2": "test",
        "property3": "world",
        "property4": "texthere",
    }
}
```
