### ISSUE TITLE
[BUG] Problem installing python library in automatic runtime

### ISSUE THREAD

**Issue by noraabiakar** [microsoft/promptflow#1075]
**Describe the bug**
Automatic Runtime missing `pydantic==2.4.2` listed in `requirements.txt`

**How To Reproduce the bug**

`flow.dag.yaml`
```
environment:
  python_requirements_txt: requirements.txt
inputs:
  input:
    type: string
    default: '{"key":"value"}'
outputs:
  output:
    type: string
    reference: ${extract_value.output}
nodes:
- name: extract_value
  type: python
  source:
    type: code
    path: extract_value.py
  inputs:
    input: ${inputs.input}
```

`extract_value.py`
```
from promptflow import tool
from pydantic import BaseModel

class KeyValModel(BaseModel):
    key: str  

@tool
def extract_value(input: str) -> float:
    report = KeyValModel.model_validate_json(input)
    return report.key
```

`requirements.txt`
```
pydantic==2.4.2
```

The flow consists of the above 3 files. The flow is run in Azure ML using an automatic runtime (run.py script can be provided if needed).

**Expected behavior**
The required libraries in requirements.txt are installed on the automatic runtime and the run completes successfully.

**Screenshots**
The run completes, but in a failed state. The `model_validate_json` function is not found (it needs pydentic v2, it seems pydantic v1 is available in the runtime). 

![image](https://github.com/microsoft/promptflow/assets/18661075/4d51e574-7d3e-49c7-b329-e2cabae7a595)
![image](https://github.com/microsoft/promptflow/assets/18661075/98b61863-4252-4577-bb7e-e9f3b933c88a)

**Running Information:**
 - Promptflow Package Version: Whatever is available on the automatic runtime by default. 
 - Operating System: Windows 11
 - Python Version using `python --version`: Python 3.10.11

**Additional context**
This may or may not be related, I can't tell without access to the automatic runtime build logs. 

I faced a similar issue on the custom runtime, using this docker context: 
```
FROM mcr.microsoft.com/azureml/promptflow/promptflow-runtime:20230919.v1
RUN pip install pydantic==2.4.2
```

I was able to figure out that the upgrade of pydantic from v1 to v2 was failing because the base image uses an older version of mlflow that has a dependency on pydantic v1. I was able to fix it by upgrading mlflow first: 

```
FROM mcr.microsoft.com/azureml/promptflow/promptflow-runtime:20230919.v1
RUN pip install mlflow==2.7.1
RUN pip install pydantic==2.4.2
```

I wasn't able to apply the same workaround with the automatic runtime.
