### ISSUE TITLE
[Feature Request] Allow OpenAI tool to be initiated with environment variables

### ISSUE THREAD

**Issue by luigiw** [microsoft/promptflow#1667]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

I have a local flow that uses multiple llm nodes, to run the flow I have to create a connection and set the connection name in the llm nodes. This is not very convenient if I need to switch across multiple OpenAI resources. OpenAI client can be initiated with environment variables, which I often have already set locally. There should be a way I can have the llm nodes to use my local environment variables so that I don't need to create connections and change llm nodes all the time.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by D-W-** [comment]
Hi @luigiw , thanks for reporting! We plan to support this in our python eager mode's phase 2, which might take a while. Currently there's a workaround, you can create a connection which references environment variable for `api_key` like this:

```yaml
$schema: https://azuremlschemas.azureedge.net/promptflow/latest/OpenAIConnection.schema.json
type: open_ai
name: open_ai_connection
api_key: ${env:OPEN_AI_CONNECTION_API_KEY} # env reference
```

Not sure if it works for your scenario, we'll add a doc for this usage.
