### ISSUE TITLE
[BUG] Custom connection doesn't work with endpoints from AML model catalog

### ISSUE THREAD

**Issue by ZhiliangWu** [microsoft/promptflow#1672]
**Describe the bug**
I developed using Promptflow locally, and it works well with Azure OpenAI connections. However, the custom connection failed. 
I created an endpoint of gpt2 using one of the models in AML model catalog. The endpoint is deployed successfully, and I filled the example yaml from the [docs](https://microsoft.github.io/promptflow/how-to-guides/manage-connections.html) with the `REST endpoint` and `Primary key` in the `Consume` page. 

```yaml
$schema: https://azuremlschemas.azureedge.net/promptflow/latest/CustomConnection.schema.json
name: custom_connection
type: custom
configs:
  endpoint: "<your-endpoint>"
secrets: 
  my_key: "<your-api-key>"
```

I added it to the Promptflow and the run failed with 

```shell
Create run failed with ResolveToolError: Tool load failed in 'llm_node_with_template': (APINotFound) The API 'None.None' is not found.
```

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a Real-time endpoint from the AML workspace
2. Fill out the `custom_connection.yaml` with the values from the deployed endpoint 

```yaml
$schema: https://azuremlschemas.azureedge.net/promptflow/latest/CustomConnection.schema.json
name: custom_connection
type: custom
configs:
  endpoint: "<your-endpoint>"
secrets: 
  my_key: "<your-api-key>"
```

3. Configure the custom connection in the Promptflow `pf connection create -f custom_connection.yaml`
4. Add a variant using this custom connection, similar to 

```yaml
      variant_2:
        node:
          type: llm
          source:
            type: code
            path: llm_node_with_template.jinja2
          inputs:
            instruction: ${inputs.instruction}
            input: ${inputs.input}
          connection: custom_connection
```

5. Create the run with this variant. 

**Expected behavior**
It should work as connections like Azure OpenAI connections. This blocks all users from using available models from the model category with promptflow.

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 1.3.0
 - Operating System: MacOS 14.2.1
 - Python Version using `python --version`: 3.9.10

**Comment by gjwoods** [comment]
Hi @ZhiliangWu - thanks for reaching out.
Can you confirm which tool you are using for accessing the AzureML model catalog endpoint?
The "LLM" tool is currently only used for OpenAI and Azure OpenAI connections. To use AzureML model catalog endpoints you can use the Open_Model_LLM Tool (found under "+ More tools").

To set expectations, the Custom Connection type is generic for different tools, for the Open Model LLM tool, the connection needs the following values:
endpoint_url = "<your-endpoint>"
model_family = "GPT2" # for GPT2
endpoint_api_key = "<your-api-key>" (secret)

Please give it a try and let me know.

**Comment by brynn-code** [comment]
The error `The API 'None.None' is not found` raised because no relevant api is found for custom connection, the message is vague, and we will improve it. And for llm node, like Gerard said, we don't support custom connection for now.

**Comment by ZhiliangWu** [comment]
@gjwoods thanks for your quick reply. I also checked the related docs at https://microsoft.github.io/promptflow/reference/tools-reference/open_model_llm_tool.html#open-model-llm. The following code works to create the custom connection with `pf connection create -f custom_connection.yaml`

```yaml
$schema: https://azuremlschemas.azureedge.net/promptflow/latest/CustomConnection.schema.json
name: custom_connection
type: custom
configs:
  endpoint_url: <url>
  model_family: GPT2
secrets:
  endpoint_api_key: <key>
```

Meanwhile, I met some issues to use it with the node with type `Open_Model_LLM` having configurations as

```yaml
- name: Open_Model_LLM
  type: custom_llm
  source:
    type: package_with_prompt
    tool: promptflow.tools.open_model_llm.OpenModelLLM.call
    path: Open_Model_LLM.jinja2
  inputs:
    api: completion
    instruction: ${inputs.instruction}
    input: ${inputs.input}
    endpoint_name: custom_connection   #not sure whether this is correct
```

The error says 

```console
2024-01-17 23:09:20 +0100   20192 execution.flow     INFO     [Open_Model_LLM in line 0 (index starts from 0)] stdout> Executing Open Model LLM Tool for endpoint: 'custom_connection', deployment: 'None'
2024-01-17 23:09:20 +0100   20192 execution          ERROR    Node Open_Model_LLM in line 0 failed. Exception: Execution failure in 'Open_Model_LLM': (IndexError) list index out of range.
...
in parse_endpoint_connection_type
    return (endpoint_connection_details[0].lower(), endpoint_connection_details[1])
IndexError: list index out of range
```

Do you know if I need to do any futher steps to configure this tool?
