### ISSUE TITLE
[BUG] 50 documents returned rather than `top_k` for `VectorDB` Tool using AI Search Connection

### ISSUE THREAD

**Issue by msha1026** [microsoft/promptflow#1843]
**Describe the bug**
In AzureML prompt flow studio, using the VectorDB lookup tool and connecting to AI Search, I set the `top_k` input value to 1. However, after a run of the flow, the output of the VectorDB lookup node shows 50 documents returned instead. I have tried various values for `top_k` but always receive 50 documents back.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a chat flow with the following structure:
  ```yaml
  id: bring_your_own_data_chat_qna
  name: Copilot Chat
  inputs:
    chat_history:
      type: list
      default:
      - role: system
        content: You are an AI assistant that helps people find information.
      - role: user
        content: hi there this is a test
      - role: assistant
        content: Hello! How can I assist you today?
      is_chat_input: false
    chat_input:
      type: string
      default: What is the capital of Germany?
      is_chat_input: false
  outputs: {}
  nodes:
  - name: embed_the_question
    type: python
    source:
      type: package
      tool: promptflow.tools.embedding.embedding
    inputs:
      connection: openai_connection
      deployment_name: text-embedding-ada-002
      input: ${inputs.chat_input}
    use_variants: false
  - name: azure_ai_search_lookup
    type: python
    source:
      type: package
      tool: promptflow_vectordb.tool.vector_db_lookup.VectorDBLookup.search
    inputs:
      connection: ai_search_connection
      index_name: chunked
      text_field: text
      vector_field: embedding
      search_params:
        search: What is the capital of Germany?
      search_filters:
        filter: ""
      vector: ${embed_the_question.output}
      top_k: 1
    use_variants: false
  node_variants: {}
  environment:
    python_requirements_txt: requirements.txt
  ```
2. Run the flow and review the output of the `azure_ai_search_lookup` node
3. Notice that 50 documents are returned instead of 1(`top_k`)
**Expected behavior**
Only `top_k` amount of documents are returned from `azure_ai_search_lookup` node

**Screenshots**
Small snippet of the array of documents returned
![image](https://github.com/microsoft/promptflow/assets/15195985/4a8508ab-7d42-4e09-bea0-c9c330454fa6)

**Running Information(please complete the following information):**
 - Azure ML prompt flow using automatic runtime

**Additional context**
N/A

**Comment by D-W-** [comment]
Hi @dans-msft @Adarsh-Ramanathan , please help to take a look of this issue. @msha1026 we currently only track prompt flow SDK/CLI issues here. For portal UI bugs, please create an OCV in portal here:
![image](https://github.com/microsoft/promptflow/assets/7776147/b6636c81-8c53-4bc8-81c0-d30b5a316fce)

**Comment by msha1026** [comment]
Thank you for the speedy replies!

@Adarsh-Ramanathan I have tried the preview Index Lookup tool in AzureML studio, and that did resolve the issue. Thank you!

Is this preview tool also supported in VSCode? If so, what packages need to be installed in order to also run this in the VSCode prompt flow extension?

For reference, this is my local dev environment:
VSCode extension: 1.9.2
`promptflow`: 1.4.1
`promptflow-tools`: 1.1.0
`promptflow-vectordb`: 0.1.2

**Comment by Adarsh-Ramanathan** [comment]
@msha1026, you might need to install pymongo as well - this should be an extra, but at present, is a required dependency. This is a known bug that will be fixed with the upcoming release. If you run `pf tool list` in your env, you should see a ModuleNotFoundError in the output complaining that pymongo wasn't found.

**Comment by msha1026** [comment]
Thanks! In addition to `pymongo`, `azureml-rag[search-documents]` was also missing. This was the final package list that I had to install in order to get the tool working in VSCode:
```
promptflow[azure]
promptflow-tools
promptflow-vectordb
azureml-rag[cognitive-search]
pymongo
```

@Adarsh-Ramanathan is there a timeline on when the Vector DB Lookup tool will be officially deprecated? Is there also a timeline for when the upcoming release will be for the dependency fix?

**Comment by Adarsh-Ramanathan** [comment]
@msha1026, the tools will be marked as deprecated with the next package release, although I don't have an exact timeline on decommissioning them altogether. The next release should be out this week, and that'll include the fix for the pymongo dependency.

WRT the other dependencies, they're bundled with the `azure` extra for promptflow-vectordb, if you install that extra, you _should_ get all of those as transitive requirements.

**Comment by jayendranarumugam** [comment]
Hi @msha1026 , When I tried the new preview Index I get the error like 

```
promptflow._utils.tool_utils.DynamicListError: Unable to display list of items due to 'Error when calling function promptflow_vectordb.tool.common_index_lookup_utils.list_available_query_types: tool_ui_callback.<locals>.wrapped() missing 3 required positional arguments: 'subscription_id', 'resource_group_name', and 'workspace_name''. Please contact the tool author/support team for troubleshooting assistance.
```

![Screenshot 2024-02-01 at 3 21 27 PM](https://github.com/microsoft/promptflow/assets/25414541/54e64311-ad65-4374-a8ff-234ea5338213)

I already have a .azureml/config.json with the below content.
```
{
  "subscription_id": "xxxxx",
  "resource_group": "rg-test",
  "workspace_name": "demo123"
}

```

**Comment by msha1026** [comment]
@jayendranarumugam Our `flow.dag.yaml` looks different from yours. This is how ours looks:
```
mlindex_content: >
  embeddings:
    api_base: https://<azure-openai-name>.api.cognitive.microsoft.com/
    api_type: azure
    api_version: 2023-07-01-preview
    batch_size: '1'
    connection:
      id: /subscriptions/<sub-id>/resourceGroups/<rg-name>/providers/Microsoft.MachineLearningServices/workspaces/<azureml-wksp-name>/connections/<azure_openai_connection_name>
    connection_type: workspace_connection
    deployment: text-embedding-ada-002
    dimension: 1536
    kind: open_ai
    model: text-embedding-ada-002
    schema_version: '2'
  index:
    api_version: 2023-07-01-preview
    connection:
      id: /subscriptions/<sub-id>/resourceGroups/<rg-name>/providers/Microsoft.MachineLearningServices/workspaces/<azureml-wksp-name>/connections/<azure-search-connection-name>
    connection_type: workspace_connection
    endpoint: https://<azure-ai-search-name>.search.windows.net
    engine: azure-sdk
    field_mapping:
      content: <name_of_field_in_search_for_document_contents>
      embedding: <name_of_embedding_field_in_search>
      metadata: <name_of_field_in_search_for_document_id>
    index: <index_name>
    kind: acs
    semantic_configuration_name: null
queries: ${modify_query_with_history.output} #This is the unembedded query. This node should handle embedding the query for you
query_type: Hybrid (vector + keyword)
top_k: 3
```
