### ISSUE TITLE
pfazure doesn't use federated identity credentials from az login

### ISSUE THREAD

**Issue by ZhiliangWu** [microsoft/promptflow#1994]
**Describe the bug**

I use service principal authentication to communicate with azure services. According to this [page](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-setup-authentication?view=azureml-api-2&tabs=sdk#use-service-principal-authentication), I can set up environment variables to realize that. Meanwhile, as I run these jobs in Gitlab CI jobs, where they support [OpenID Connect to retrieve temporary credentials](https://docs.gitlab.com/ee/ci/cloud_services/azure/#retrieve-a-temporary-credential), I think this should also work. In CI jobs, it logs in successfully by running

```console
 az login --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID --federated-token $GITLAB_OIDC_TOKEN
```
but when I follow https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/how-to-integrate-with-llm-app-devops?view=azureml-api-2&tabs=cli#connect-to-azure-machine-learning-workspace and run 

```console
pfazure run create --file run.yml
```

I got 

```console
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
	ManagedIdentityCredential: Unexpected content type "text/html; charset=UTF-8"
```

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Follow https://docs.gitlab.com/ee/ci/cloud_services/azure/#create-azure-ad-application-and-service-principal to configure OpenID Connect for respective repo
2. Create .gitlab-ci.yml file as

```yaml
default:
  image: python:3.9
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
variables:
  AZURE_CLIENT_ID: <>
  AZURE_TENANT_ID: <>
  SUBSCRIPTION: <>
  RESOURCE_GROUP: <>
  WORKSPACE: <>

tests:
  script:
    - pip install promptflow promptflow-tools azure-cli azure-ai-ml azure-identity
    - az login --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID --federated-token $GITLAB_OIDC_TOKEN
    - az account show
    - az account set --subscription $SUBSCRIPTION
    - az configure --defaults workspace=$WORKSPACE group=$RESOURCE_GROUP
    - pfazure run create --file run.yml

```

**Expected behavior**
It should upload the flow folder to the corresponding Azure Machine Learning workspace and run the flow there. 

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 1.5.0
 - Operating System: Docker image: python:3.9
 - Python Version using `python --version`: 3.9.18

**Additional context**
This relates to https://github.com/Azure/azure-sdk-for-python/issues/33332, where the `DefaultAzureCredential` got stuck at `managed_identity_credential` when I log in using the federated identity. Is there any way to configure this in the `pfazure` command? In the mentioned issue, the solution was to use `credential = DefaultAzureCredential(exclude_managed_identity_credential=True)` or `credential = AzureCliCredential()`. Can do have some such settings in the `pfazure` command? I would prefer the CLI solution as it makes the command more concise in comparison to Python SDK.  Or are there any environment variable we can set to disable such behavior?
