### ISSUE TITLE
[BUG] Promptflow ParserError/IndexError

### ISSUE THREAD

**Issue by Kevinlee49** [microsoft/promptflow#2046]
I'm using hybrid search and semantic search simultaneously and got this error. Do you happen to know what is the solution for this?

<img width="1638" alt="2024-02-19_15-39-40" src="https://github.com/microsoft/promptflow/assets/86863395/2c3e20ef-ee4d-45e0-a1ad-64a4ea584246">

This is the output from semantic search node.

> "Execution failure in 'semantic_search': (IndexError) string index out of range"

This is the output from hybrid search node.

> "Execution failure in 'hybrid_search': (ParserError) while parsing a block mapping\n  in \"<unicode string>\", line 2, column 3:\n      api_base: ... \n      ^ (line: 2)\nexpected <block end>, but found '<scalar>'\n  in \"<unicode string>\", line 9, column 15:\n      deployment: text-embedding-ada-002\n                  ^ (line: 9)"

**Comment by brynn-code** [comment]
Hi, please provide the tool name you are using, seems semantic_search and hybrid_search are the names of your flow node.

**Comment by Kevinlee49** [comment]
@brynn-code Hello, thanks for reply. oh yes, I didn't clarify the tool. These two nodes are index lookup tools.

**Comment by brynn-code** [comment]
@dans-msft and @Adarsh-Ramanathan , could you please help on the index lookup tool issue? Thanks!

**Comment by Adarsh-Ramanathan** [comment]
@Kevinlee49, can you share a minimal flow yaml that results in a repro so we can look into this?

**Comment by Kevinlee49** [comment]
Here it is,

```
environment:
  python_requirements_txt: requirements.txt
inputs:
  question:
    type: string
    is_chat_input: false
    default: blah blah blah
outputs:
  output:
    type: string
    reference: ${answer_the_question_with_context.output}
    evaluation_only: false
    is_chat_output: true
nodes:
- name: answer_the_question_with_context
  type: llm
  source:
    type: code
    path: answer_the_question_with_context.jinja2
  inputs:
    deployment_name: gpt-35-turbo-16k-v0613
    temperature: 0.7
    top_p: 1
    max_tokens: 1000
    response_format:
      type: text
    presence_penalty: 0
    frequency_penalty: 0
    final_prompt: ${final_prompt.output}
  provider: AzureOpenAI
  connection: test-connection
  api: chat
  module: promptflow.tools.aoai
  aggregation: false
  use_variants: false
- name: input_classify_and_rephrase
  type: prompt
  source:
    type: code
    path: input_classify_and_rephrase.jinja2
  inputs:
    question: ${inputs.question}
  use_variants: false
- name: semantic_search
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.common_index_lookup.search
  inputs:
    mlindex_content: >
      embeddings:
        api_base: https://
        api_type: azure
        api_version: 2023-07-01-preview
        batch_size: '16'
        connection:
          id: /subscriptions/
        connection_type: workspace_connection
        deployment: text-embedding-ada-002
        dimension: 1536
        file_format_version: '2'
        kind: open_ai
        model: text-embedding-ada-002
        schema_version: '2'
      index:
        api_version: 2023-07-01-preview
        connection:
          id: /subscriptions/
        connection_type: workspace_connection
        endpoint: https://
        engine: azure-sdk
        field_mapping:
          content: content
          embedding: contentVector
          filename: filepath
          metadata: meta_json_string
          title: title
          url: url
        index: pf-rpindex
        kind: acs
        semantic_configuration_name: azureml-default
    queries: ${python_query_analyze_and_rephrase.output}
    query_type: Semantic
    top_k: 3
  use_variants: false
- name: hybrid_search
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.common_index_lookup.search
  inputs:
    mlindex_content: >
      embeddings:
        api_base: https://
        api_type: azure
        api_version: 2023-07-01-preview
        batch_size: '16'
        connection:
          id: /subscriptions/
        connection_type: workspace_connection
        deployment: text-embedding-ada-002
        dimension: 1536
        file_format_version: '2'
        kind: open_ai
        model: text-embedding-ada-002
        schema_version: '2'
      index:
        api_version: 2023-07-01-preview
        connection:
          id: /subscriptions/
        connection_type: workspace_connection
        endpoint: https://
        engine: azure-sdk
        field_mapping:
          content: content
          embedding: contentVector
          filename: filepath
          metadata: meta_json_string
          title: title
          url: url
        index: pf-rpindex
        kind: acs
        semantic_configuration_name: azureml-default
    queries: ${input_classify_and_rephrase.output}
    query_type: Hybrid (vector + keyword)
    top_k: 3
  use_variants: false
- name: generate_context
  type: python
  source:
    type: code
    path: generate_context.py
  inputs:
    hybrid_search_output: ${hybrid_search.output}
    semantic_search_output: ${semantic_search.output}
  use_variants: false
- name: final_prompt
  type: prompt
  source:
    type: code
    path: final_prompt.jinja2
  inputs:
    context: ${generate_context.output}
    question: ${inputs.question}
  use_variants: false
- name: python_query_analyze_and_rephrase
  type: python
  source:
    type: code
    path: python_query_analyze_and_rephrase.py
  inputs:
    question: ${inputs.question}
  use_variants: false
```

**Comment by Kevinlee49** [comment]
@Adarsh-Ramanathan Hello, did you get the solution for this issue?

**Comment by Adarsh-Ramanathan** [comment]
@Kevinlee49 , not yet. I'll post an update once I've investigated.

**Comment by Adarsh-Ramanathan** [comment]
@Kevinlee49 , I'm assuming you have actual URLs etc in the various mlindex fields (like `api_base` and similar), and you've just redacted them before posting on here. I'm having a hard time reproing this issue; can you capture the outputs of the `python_query_analyze_and_rephrase` and `input_classify_and_rephrase` steps when executing your flow?

**Comment by Kevinlee49** [comment]
Of course, I have my actual urls, etc in my fields. Just the only thing is I realized that only in hybrid search part is problematic. It kept saying that I need vector fields.

**Comment by Kevinlee49** [comment]
@Adarsh-Ramanathan outputs of the `python_query_analyze_and_rephrase` and `input_classify_and_rephrase` are respectively [topic_keyword] [question], like weather [how's the weather today?] , for input_classify_and_rephrase output is just prompt. Because it is a jinja2 file.

**Comment by Kevinlee49** [comment]
@Adarsh-Ramanathan ![image](https://github.com/microsoft/promptflow/assets/86863395/80cf1c69-bc2a-4edc-a889-fe2715bbc089)

**Comment by Adarsh-Ramanathan** [comment]
Can you share a run's example output for `input_classify_and_rephrase`? I'm not able to repro this issue, our best bet is to eliminate variables and isolate the problem down to the actual lookup nodes, and run it with a configuration that's as close to the one you're running, inputs and all.

Can you also provide info about the runtime version you're using, and if you've installed/updated/overriden any packages?

To answer your question, no - introducing multiple instances of index lookup is definitely supported - the reason hybrid is failing and semantic is not is that ACS doesn't need a vector input for semantic search, while hybrid does. The issue is that your MLIndex looks like it's configured correctly, so we _should_ have been able to produce a vector to send to ACS - this is what we need to get to the bottom of.

**Comment by Kevinlee49** [comment]
@Adarsh-Ramanathan On VScode the errors look like this 
![image](https://github.com/microsoft/promptflow/assets/86863395/8ee67c60-bc03-4107-9b58-1611bf9b48da)
![image](https://github.com/microsoft/promptflow/assets/86863395/d012d6bc-db06-46d7-bff7-7cf542c7643a)
![image](https://github.com/microsoft/promptflow/assets/86863395/22044132-fc1e-4a22-ba85-20a571503fdf)

**Comment by Kevinlee49** [comment]
@Adarsh-Ramanathan 

_Can you share a run's example output for input_classify_and_rephrase?_ 
-> 
> assistant: ~~~
> system:  ~~~~
> conversation: ~~~
> user: ~~~

_Can you also provide info about the runtime version you're using, and if you've installed/updated/overriden any packages?_ -> how can I show this?
.

**Comment by Adarsh-Ramanathan** [comment]
```
assistant: ~~~
system: ~~~~
conversation: ~~~
user: ~~~
```

Is this a string? A list of strings? An object?

--------


`Can you also provide info about the runtime version you're using, and if you've installed/updated/overriden any packages? -> how can I show this?`
You could add a python step with these contents to your flow, and grab it's stdout:
```
@tool
def my_python_tool(input1: str) -> str:
    from pip._internal.operations import freeze
    pkgs = freeze.freeze()
    for pkg in pkgs: print(pkg)
```

**Comment by Adarsh-Ramanathan** [comment]
@Kevinlee49 , I'm still unable to reproduce your error.

Here's the minimal flow I built off of your example:
![image](https://github.com/microsoft/promptflow/assets/68247982/99d909b6-9490-4086-b270-a67f314fb67d)


Flow yaml:
```
inputs:
  question:
    type: string
    default: blah blah blah
    is_chat_input: false
outputs:
  output:
    type: string
    reference: ${generate_context.output}
    evaluation_only: false
    is_chat_output: true
nodes:
- name: input_classify_and_rephrase
  type: prompt
  source:
    type: code
    path: input_classify_and_rephrase.jinja2
  inputs:
    question: ${inputs.question}
  use_variants: false
- name: hybrid_search
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.common_index_lookup.search
  inputs:
    mlindex_content: >
      embeddings:
        api_base: ****
        api_type: azure
        api_version: 2023-07-01-preview
        batch_size: '16'
        connection:
          id: ****
        connection_type: workspace_connection
        deployment: text-embedding-ada-002
        dimension: 1536
        file_format_version: '2'
        kind: open_ai
        model: text-embedding-ada-002
        schema_version: '2'
      index:
        api_version: 2023-07-01-preview
        connection:
          id: ****
        connection_type: workspace_connection
        endpoint: ****
        engine: azure-sdk
        field_mapping:
          content: content
          embedding: contentVector
          filename: filepath
          metadata: meta_json_string
          title: title
          url: url
        index: ****
        kind: acs
        semantic_configuration_name: azureml-default
    queries: ${input_classify_and_rephrase.output}
    query_type: Hybrid (vector + keyword)
    top_k: 3
  use_variants: false
- name: generate_context
  type: python
  source:
    type: code
    path: generate_context.py
  inputs:
    search_result: ${hybrid_search.output}
  use_variants: false
node_variants: {}
environment:
  python_requirements_txt: requirements.txt
```

requirements.txt:
```
promptflow_vectordb[azure]
```

generate_context.py:
```
from typing import List
from promptflow import tool
import json
from pip._internal.operations import freeze

@tool
def generate_prompt_context(search_result: List[dict]) -> str:
    return json.dumps(list(freeze.freeze()))
```

input_classify_and_rephrase.jinja2:
```
system: You are a helpful bot that finds answers to questions.
user: {{ question }}
assistant:
```

I'm running this with an automatic runtime in westus2. Can you try running this flow and see if your issue still persists?

Your issue in vscode is unrelated, IIRC, you need to configure a number of azure defaults beforehand to get things to play nice: https://microsoft.github.io/promptflow/how-to-guides/develop-a-tool/create-dynamic-list-tool-input.html#faqs
