### ISSUE TITLE
[BUG] Run environment variables not sent by pfazure to Azure ML 

### ISSUE THREAD

**Issue by danigian** [microsoft/promptflow#2118]
**Describe the bug**
Environment variables for the run are not submitted/propagated to Azure ML.
Until friday afternoon (February 23), the bug was not there.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a flow `pf flow init --flow variabletest`
2. Add a run.yaml like the following:
```yml
$schema: https://azuremlschemas.azureedge.net/promptflow/latest/Run.schema.json
flow: .
data: data.jsonl
environment_variables:
  WHATEVER: "test"
column_mapping:
  text: ${data.text}
```
3. Adjust the `variabletest/hello.py` for printing the environment variable `WHATEVER`
4. Run `pfazure run create -f variabletest/run.yml --subscription $SUBSCRIPTION_ID --resource-group $RESOURCE_GROUP --workspace-name $AZURE_ML_WORKSPACE  --stream`
5. Enjoy the KeyError when trying to access environment variable

**Expected behavior**
Environment variables are available as before

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 1.5.0
 - Operating System: Ubuntu WSL
 - Python Version using `python --version`: 3.9.18
