### ISSUE TITLE
[BUG] Embedding not a ToolType

### ISSUE THREAD

**Issue by axecopfire** [microsoft/promptflow#2373]
**Describe the bug**
I would like to use the embedding tool type but I'm unclear on how to access it.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
```
nodes:
- name: embedding_step
  type: embedding
  inputs:
    input: "text"
    connection: open_ai_connection
    deployment_name: embeddingdeployment
```

Error: `ValueError: 'embedding' is not a valid ToolType`

Via the documentation it looks like `embedding` would be a tool type. But in the list of enums I can tell it's not https://github.com/microsoft/promptflow/blob/4cf6b54cdcf9261baae6266667d42d7753a176b0/src/promptflow/promptflow/contracts/tool.py#L232

**Expected behavior**
I'm expecting that it would be a tool type. If it's not that can someone help clarify what it is and how to use at a node level? 

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 1.6.0
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: 3.9.8

**Additional context**
