### ISSUE TITLE
[BUG] List variable inputs aren't interpreted for python nodes

### ISSUE THREAD

**Issue by axecopfire** [microsoft/promptflow#2400]
**Describe the bug**
Input variables are not being interpolated for python node inputs.

**How To Reproduce the bug**
```
- name: process_topic
  type: python
  source:
    type: code
    path: src/process_detected_topics.py
  inputs:
    topics:
    - ${topic_detection_1.output}
    - ${topic_detection_2.output}
```

Results in the input for `topics`: `["${topic_detection_1.output}","${topic_detection_2.output}"]`.

**Expected behavior**
`topic_detection_[N].output` should be interpolated to the output values of those nodes.

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

**Additional context**
