### ISSUE TITLE
[Feature Request] Allow configuration of log format

### ISSUE THREAD

**Issue by FriederikeBrezing** [microsoft/promptflow#2852]
**Is your feature request related to a problem? Please describe.**
We are exporting logs to datadog, and are planning to inject OTEL trace information into our logs. This requires that logs use a certain format. We can configure the format of logs in our custom code but the log format for logs from the promptflow executor or serving app use their own format.
Examples: 
`2024-04-17 09:52:48 +0100    8826 execution.flow     INFO     Start executing nodes in thread pool mod`
`[2024-04-17 09:51:16,380][pfserving-app][INFO] - Promptflow executor starts initializing...`

**Describe the solution you'd like**
An option and clear instructions for how to customise the log format of logs created by promptflow. Ideally a way to provide a log config file which will be used by promptflow to configure logging so what we can get it to use any log format or handlers. 

**Describe alternatives you've considered**
We tried to wrap calls to promptflow in a python app and configured the logging before calling promptflow but this did not affect the logging configuration used by promptflow.

**Comment by PeiwenGaoMS** [comment]
Hi @FriederikeBrezing , 

Thank you for your feedback. Based on the issues you raised, we have thought of three potential solutions:

- Add environment variables in the flow yaml, for example:
``` yaml
inputs:
  text:
    type: string
outputs:
  output_text:
    type: string
    reference: ${print_input.output}
nodes:
- name: print_input
  type: python
  source:
    type: code
    path: print_input.py
  inputs:
    text: ${inputs.text}
environment_variables:
  PF_LOG_FORMAT: "[%(asctime)s][%(name)s][%(levelname)s] - %(message)s"
  PF_LOG_DATETIME_FORMAT: "%Y/%m/%d %H:%M:%S"

```
- Pass the format you need through a function provided before submitting the flow, for example:
``` python
from promptflow.core import set_log_format
from promptflow.client import PFClient

set_log_format(fmt=..., datefmt=...)

pf = PFClient()
flow_path = ...
flow_inputs = ...
flow_result = pf.test(flow=flow_path, inputs=flow_inputs)
```
- Place a `log_config.json` in the flow folder, for example:
``` json
{
    "log_format": "[%(asctime)s][%(name)s][%(levelname)s] - %(message)s",
    "date_format": "%Y/%m/%d %H:%M:%S"
}
```

Based on the three options provided, we will change the format of the promptflow logger after receiving the format you pass. Which of these three solutions would you prefer?
