### ISSUE TITLE
[BUG] AI Search connection in `mlindex_content` not detected

### ISSUE THREAD

**Issue by adamdougal** [microsoft/promptflow#3313]
**Describe the bug**
I have a `Multi-Round Q&A on Your Data` chat flow which queries Azure AI Search and passes the results, along with the chat history and question to Azure OpenAI. After exporting the flow, with the intention of deploying to Azure App Service. I am unable to successfully run a built flow (either as an executable or docker image). I believe this is due to the Azure AI Search connection being ignored.

When running `pf flow serve` the flow runs correctly and I am able to get responses.

I have tried this with prompt flow verisons `1.9.0`, `1.10.0` and `1.11.0`.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a `Multi-Round Q&A on your data` chat flow.
2. Export the flow locally
3. Install the requirements `pip install -r requirements.txt`
4. Create the AI Search and Open AI connections files
5. Add the connections to prompt flow `pf connection create -f <file>`
6. Build the flow `pf flow build --source . --output dist-docker --format docker`
7. Inspect the `dist-docker/connections` directory and observe that the AI Search connection is missing

**Expected behavior**
The AI search connection is picked up and connection file created.

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 ``` bash
$ pf -v
{
  "promptflow": "1.9.0",
  "promptflow-core": "1.9.0",
  "promptflow-devkit": "1.9.0",
  "promptflow-tracing": "1.9.0"
}
```
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 ``` bash
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
 - Python Version using `python --version`: [e.g. python==3.10.12]
```bash
$ python --version
Python 3.11.8
```

**Additional context**
Example files, click to expand:

<details>
<summary>A shorterned and redacted example prompt flow</summary>

```yaml
id: bring_your_own_data_chat_qna
name: Bring Your Own Data Chat QnA
inputs:
  chat_history:
    type: list
    default:
    - inputs:
        chat_input: Hi
      outputs:
        chat_output: Hello! How can I assist you today?
    - inputs:
        chat_input: What is Azure compute instance?
      outputs:
        chat_output: An Azure Machine Learning compute instance is a fully managed
          cloud-based workstation for data scientists. It provides a
          pre-configured and managed development environment in the cloud for
          machine learning. Compute instances can also be used as a compute
          target for training and inferencing for development and testing
          purposes. They have a job queue, run jobs securely in a virtual
          network environment, and can run multiple small jobs in parallel.
          Additionally, compute instances support single-node multi-GPU
          distributed training jobs.
    is_chat_input: false
    is_chat_history: true
  chat_input:
    type: string
    default: How can I create one using azureml sdk V2?
    is_chat_input: true
outputs:
  chat_output:
    type: string
    reference: ${chat_with_context.output}
    is_chat_output: true
nodes:
- name: index_lookup
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.common_index_lookup.search
  inputs:
    mlindex_content: >
      embeddings:
        api_base: https://<openai-resource-redacted>.openai.azure.com/
        api_type: azure
        api_version: '2024-02-01'
        batch_size: '1'
        connection:
          id: /subscriptions/<subscription-redacted>/resourceGroups/<resource-group-redacted>/providers/Microsoft.MachineLearningServices/workspaces/<aml-workspace-redacted>/connections/openai_connection
        connection_type: workspace_connection
        deployment: text-embedding-ada-002
        dimension: 1536
        kind: open_ai
        model: text-embedding-ada-002
        schema_version: '2'
      index:
        api_version: '2023-11-01'
        connection:
          id: /subscriptions/<subscription-redacted>/resourceGroups/<resource-group-redacted>/providers/Microsoft.MachineLearningServices/workspaces/<aml-workspace-redacted>/connections/aisearch_connection
        connection_type: workspace_connection
        endpoint: https://<ai-search-resource-redacted>.search.windows.net
        engine: azure-sdk
        field_mapping:
          content: content
          embedding: content_vector
          metadata: metadata
        index: <search-index-redacted>
        kind: acs
        semantic_configuration_name: default
    queries: ${inputs.chat_input}
    query_type: Hybrid (vector + keyword)
    top_k: 2
  use_variants: false
- name: chat_with_context
  type: llm
  source:
    type: code
    path: chat_with_context.jinja2
  inputs:
    deployment_name: gpt-35-turbo-16k
    temperature: 0
    top_p: 1
    max_tokens: 1000
    presence_penalty: 0
    frequency_penalty: 0
    prompt_text: ${Prompt_variants.output}
  provider: AzureOpenAI
  connection: openai_connection
  api: chat
  module: promptflow.tools.aoai
  use_variants: false
node_variants: {}
environment:
  python_requirements_txt: requirements.txt
```
</details>

<details>
<summary>AI Search Connection</summary>

```yaml
$schema: https://azuremlschemas.azureedge.net/promptflow/latest/CognitiveSearchConnection.schema.json
name: aisearch_connection
type: cognitive_search
api_key:  ${env:AISEARCH_CONNECTION_API_KEY}
api_base: "https://<search-resource-redacted>.search.windows.net"
api_version: "2023-03-15-preview"
```

</details>
