### ISSUE TITLE
[FeatureAsk] Unable to use tracing in a promptflow endpoint that has been deployed to Azure Machine Learning

### ISSUE THREAD

**Issue by ccaitlien** [microsoft/promptflow#3398]
**Describe the bug**
Currently, there's no documentation or functionality to enable tracing within a promptflow endpoint that has been deployed to Azure Machine Learning. There's a way to specify Azure Machine Learning as the trace destination locally, but not when you're running promptflow as an endpoint. I tried adding my `pf.yaml` file to /src/my_flow/.promptflow, hoping there would be something in `pf flow build` that would recognize my promptflow configuration YAML file, but that didn't work either.

**How To Reproduce the Bug** 
1. Set the trace destination to your Azure Machine Learning workspace
```bash
pf config set trace.destination=azureml://subscriptions/<your_subscription_id>/resourcegroups/<your_resourcegroup_name>/providers/Microsoft.MachineLearningServices/workspaces//<your_azureml_workspace_name
```

2. Build the flow in the Docker format
`pf flow build --source ./src/my_flow --output ./build/my_flow --format docker`

3. Deploy the flow as a model in Azure Machine Learning
```YAML
# model.yml
$schema: https://azuremlschemas.azureedge.net/latest/model.schema.json
name: my_flow
version: 1
path: ../flow
description: Chat flow
properties:
  azureml.promptflow.source_flow_id: my_flow
  azureml.promptflow.mode: chat
  azureml.promptflow.chat_input: question
  azureml.promptflow.chat_output: answer
```
```bash
az ml model create --subscription <subscriptionId> --resource-group <resourceGroupName> --workspace-name <amlWorkspaceName> --file model.yml
```

4. Create online endpoint
```YAML
# endpoint.yml
$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineEndpoint.schema.json
name: my_flow
auth_mode: key
location: eastus2
traffic:
  my_flow: 100
properties:
  enforce_access_to_default_secret_stores: enabled
```
```bash
az ml online-endpoint create --subscription <subscriptionId> --resource-group <resourceGroupName> --workspace-name <amlWorkspaceName> --file endpoint.yml
```

5. Create online deployment
```YAML
# deployment.yml
$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: my_flow
endpoint_name: my_flow
model: azureml:my_flow:1
environment: azureml:my_env@latest
app_insights_enabled: true
data_collector:
  collections:
    request:
      enabled: "True"
    response:
      enabled: "True"
    model_inputs:
      enabled: "True"
    model_outputs:
      enabled: "True"
request_settings:
  request_timeout_ms: 90000
instance_type: Standard_DS3_v2
instance_count: 1
environment_variables:
  AZUREML_MDC_ENABLED: "true"
  PROMPTFLOW_MDC_ENABLE: "true"
  PROMPTFLOW_RUN_MODE: serving
```
```bash
az ml online-deployment create --subscription <subscriptionId> --resource-group <resourceGroupName> --workspace-name <amlWorkspaceName>  --file deployment.yml
```

**Expected behavior**
When running `pf flow build`, I'd expect `pf.yaml` to be used somehow to set up the tracing connection between my promptflow endpoint and the Tracing feature in Azure Machine Learning. That way, whenever I use my promptflow endpoint in the "Test" tab of Azure Machine Learning or in an application that is calling the endpoint, I can go into Azure Machine Learning to monitor the flow.

![image](https://github.com/microsoft/promptflow/assets/110753835/920fa953-0ca1-41ed-9cb1-c760fc9c61d2)

**Running Information (please complete the following information):**
 - Promptflow Package Version using `pf -v`: 
 {
  "promptflow": "1.11.0",
  "promptflow-azure": "1.11.0",
  "promptflow-core": "1.11.0",
  "promptflow-devkit": "1.11.0",
  "promptflow-tracing": "1.11.0"
}
 - Operating System: Ubuntu 22.04
 - Python Version using `python --version`: Python 3.10.12
