### ISSUE TITLE
[BUG] examples/flex-flows/chat-minimal missing flow.flex.yaml

### ISSUE THREAD

**Issue by jomalsan** [microsoft/promptflow#3569]
**Describe the bug**
The chat-minimal example is missing a flow.flex.yaml file to define the flow. When executing the example you get the following:

```bash
(.venv) **@** chat-minimal % pf run create -f run.yml
Starting prompt flow service...
Start prompt flow service on 127.0.0.1:23336, version: 1.13.0.
You can stop the prompt flow service with the following command:'pf service stop'.

You can view the traces in local from http://127.0.0.1:23336/v1.0/ui/traces/?#run=chat_minimal_variant_0_20240722_114143_815994
pf.run.create failed with UserErrorException: Have found neither flow.dag.yaml nor flow.flex.yaml in /**/**/chat-minimal
```

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Try to run the `chat-minimal` example and it will fail
2.`pf run create -f run.yml`

**Expected behavior**
Expect the flow to execute. I added the following file as flow.flex.yaml and it worked:

```yaml
$schema: https://azuremlschemas.azureedge.net/promptflow/latest/Flow.schema.json
entry: flow:chat
sample:
  inputs:
    question: "What is prompt flow?"
environment:
  python_requirements_txt: requirements.txt
```

**Running Information(please complete the following information):**
{
  "promptflow": "1.13.0",
  "promptflow-azure": "1.12.0",
  "promptflow-core": "1.13.0",
  "promptflow-devkit": "1.13.0",
  "promptflow-tracing": "1.13.0"
}

Executable '/**/.venv/bin/python3.11'
Python (Darwin) 3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)]

**Additional context**
