### ISSUE TITLE
[BUG] YAML Variable Interpolation Fails for List Inputs in PromptFlow Python Nodes

### ISSUE THREAD

**Issue by ivanko-94** [microsoft/promptflow#3841]
**Describe the bug**
When attempting to pass a list to a Python node in a PromptFlow YAML file, variable references (e.g., ${inputs.num_1}) are not interpolated correctly. Whereas the same interpolation for direct function inputs is done correctly. Instead of evaluating to actual values, the List/Dict elements are parsed as strings.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:

1. create a `flow.dag.yaml` file:

```yaml
$schema: https://azuremlschemas.azureedge.net/promptflow/latest/Flow.schema.json

inputs:
  num_1:
    type: int
  num_2:
    type: int

outputs:
  out_sum1:
    type: string
    reference: ${sum1.output}
  out_sum2:
    type: string
    reference: ${sum2.output}

nodes:
  - name: sum1
    description: this node is executed correctly because list elements are static at graph parse time
    type: python
    source:
      type: code
      path: ./fn_with_list_input.py
    inputs:
      list_arg:
        - 1
        - 2

  - name: sum2
    description: this node is not executed correctly because list elements are treated as strings
    type: python
    source:
      type: code
      path: ./fn_with_list_input.py
    inputs:
      list_arg:
        - ${inputs.num_1}
        - ${inputs.num_2}
```

2. create a script for the custom tool `./fn_with_list_input.py`

```python
from typing import List

from promptflow.core import tool


@tool
def sum_fn(list_arg: List):
    return sum(list_arg)
```

3. create a `data.jsonl`

```json
{ "num_1": 1, "num_2": 2 }
```

4. `main.py`

```python
from promptflow.client import PFClient

if __name__ == "__main__":

    promptflow_client = PFClient()
    promptflow_client.run(
        flow="./",
        data="./data.jsonl",
        stream=True,
    )
```

5. run `main.py`

**Expected behavior**
Both nodes (`sum1` and `sum2`) should get inputs 1 and 2 and return their sum. Node `sum2` should replace values for `${inputs.num_1}` and `${inputs.num_2}`.

**Actual behavior**
Node `sum1` executes as expected. Node `sum2` throws an exception: `(TypeError) unsupported operand type(s) for +: 'int' and 'str'`
upon further inspection in tracer PF did not replace ${inputs.num_1} with its actual value and has treated it as string:

```json
{
"list_arg": [
0: "${inputs.num_1}",
1: "${inputs.num_2}",
]
}
```

**Screenshots**
![Image](https://github.com/user-attachments/assets/66c46be5-d88e-4c92-9dac-49ddd4fd032c)

**Running Information(please complete the following information):**

- Promptflow Package Version using `pf -v`: 1.16.1
- Operating System: WSL Ubuntu 22.04
- Python Version using `python --version`: 3.10.15
