### ISSUE TITLE
[BUG] VS Code Batch Run yaml always invalid with or without schema

### ISSUE THREAD

**Issue by canwaf** [microsoft/promptflow#3955]
**Describe the bug**
When attempting to run a batch process using the YAML file, there are two main issues:
1. If the `$schema` field is provided as `$schema: https://azuremlschemas.azureedge.net/promptflow/latest/Run.schema.json`, an error `Invalid resource type provided through the file's schema.` is encountered.
2. If the `$schema` field is omitted, the error `The YAML file does not contain a "$schema" tag or "yaml-language-server" comment. Please update the file before creating the resource.` is encountered.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. From the flow.yaml GUI editor, click on batch run, select the appropriate data source.
2. Complete the data mapping as required.
3. Attempt to run the batch process.

The issues:
a. Using `$schema: https://azuremlschemas.azureedge.net/promptflow/latest/Run.schema.json` results in `Invalid resource type provided through the file's schema.` when attempting to run.
b. Omitting the `$schema` field results in `The YAML file does not contain a "$schema" tag or "yaml-language-server" comment. Please update the file before creating the resource.`

**Expected behavior**
The YAML file should be parsed and processed without errors, and the schema should correctly validate the resource types. Or the method of creating a valid batch file run using VSC should be documented.

**Running Information (please complete the following information):**
- Promptflow Package Version using `pf -v`: 1.17.2
- Operating System: Ubuntu 20.04
- Python Version using `python --version`: 3.12.6

**Additional context**
The issue occurs when processing a YAML file with the following schema:

```yaml
$schema: https://azuremlschemas.azureedge.net/promptflow/latest/Run.schema.json
name: thematic-llm-classification_default_20250214_140548_196000
display_name: thematic-llm-classification_${variant_id}_${timestamp} # supported macros: ${variant_id},${timestamp},${run}
flow: /thematic-llm-classification
data: /input.jsonl
#run: <Uncomment to select a run input>
column_mapping:
  input: ${data.input}
```
