### ISSUE TITLE
[BUG] Flow with vectordb tool failed to run due to no MLIndex found

### ISSUE THREAD

**Issue by 0mza987** [microsoft/promptflow#808]
**Describe the bug**
A clear and concise description of the bug.

Flow with vectordb tool failed to run due to no MLIndex found

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:

1. Clone portal flow sample "Bring Your Own Data Chat QnA" to local
2. Have `promptflow=0.1.0b7.post1` and `promptflow-tools==0.1.0b8` installed
3. Install `promptflow-vectordb` with `pip install promptflow-vectordb[azure]`, for me, this installed `promptflow-vectordb==0.1.2` and related azure dependencies.
4. Set up all necessary connections.
5. Click "Run all" button in VSC extension visual editor UI

Got error:
Flow test failed with ResolveToolError: Tool load failed in 'search_question_from_indexed_docs': (ToolLoadError) Failed to load package tool 'Vector Index Lookup': (FileNotFoundError) [Errno 2] No such file or directory: 'C:\\Users\\hod\\AppData\\Local\\Temp\\tmp3n3z3pl8\\MLIndex'

![image](https://github.com/microsoft/promptflow/assets/2572521/1398d63e-0d1e-49c9-b824-15cf4a5f3f09)

### Vectordb node definition:

```yaml
- name: search_question_from_indexed_docs
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.vector_index_lookup.VectorIndexLookup.search
  inputs:
    path: https://ragsample.blob.core.windows.net/ragdata/index
    query: ${embed_the_question.output}
    top_k: 2
```

**Expected behavior**

Flow can be run successfully.

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 0.1.0b7.post1
 - Operating System: Windows 11
 - Python Version using `python --version`: python==3.9.18

**Additional context**

This is a follow up issue after https://github.com/microsoft/promptflow/issues/775
