### ISSUE TITLE
[BUG] node inputs variables replace failed!

### ISSUE THREAD

**Issue by zhangjunqiang** [microsoft/promptflow#879]
```yaml
...
- name: classification_tool
  type: python
  source:
    type: package
    tool: llmops_pf_ext.tools.llm_tool.llm_tool
  inputs:
    prompt: '请扮演一个问题分类机器人的角色，根据用户提出的问题，将用户的问题分为以下类型中的一种。\n\n1. 闲聊\n2. 商品问答\n3. 翻译\n\n以下为一些简单的分类示例:\n------------\nquestion: 将 “爸爸” 翻译为英文\nanswer: 翻译\n------------\nquestion: 请问，有存钱罐推荐么？\nanswer: 商品问答\n------------\nquestion: 今天天气怎么样？\nanswer: 闲聊\n------------\n\n开始你的回答！\nquestion: {{rewrite_question}}\nanswer:'
    variables:
      rewrite_question: ${rewrite_question_tool.output.rewrite_question}
    llm_config:
      temperature: 0.8
      model: gpt-3.5-turbo-0301
      max_tokens: 1024
...
```
when i run the flow, the variable `rewrite_question` in the log is `${rewrite_question_tool.output.rewrite_question}`, did not replace with the upstream node output.

**Comment by zhangjunqiang** [comment]
the tool signature like:

```python
@tool
def netease_llm_tool(prompt: str, variables: dict, llm_config: dict) -> dict:
```

**Comment by zhangjunqiang** [comment]
the tool function's signature:
```python
@tool
def llm_tool(prompt: str, variables: dict, llm_config: dict) -> dict:
...
```

**Comment by zhangjunqiang** [comment]
![image](https://github.com/microsoft/promptflow/assets/5388898/a254c3a1-fba9-41d9-9a46-3b62347f3519)
only support primitive value ?

**Comment by zhangjunqiang** [comment]
![image](https://github.com/microsoft/promptflow/assets/5388898/5105d778-d434-4b06-81c3-9fdf02a45b24)
i also want replace in the list

**Comment by thy09** [comment]
Hello @zhangjunqiang sorry for the inconvenience, however the reference is only supported as the input value, using a reference in a complicated object is not supported.
As a workaround, you may try to add more nodes to achieve this:
For list:
```
@tool
def construct_list(item1, item2, item3):
    return [item1, item2, item3]
```
For dict:
```
@tool
def construct_dict(**kwargs):
    return kwargs
```

Would you mind sharing your user scenario to help us understand why you want this feature?

**Comment by zhangjunqiang** [comment]
> Hello @zhangjunqiang sorry for the inconvenience, however the reference is only supported as the input value, using a reference in a complicated object is not supported. As a workaround, you may try to add more nodes to achieve this: For list:
> 
> ```
> @tool
> def construct_list(item1, item2, item3):
>     return [item1, item2, item3]
> ```
> 
> For dict:
> 
> ```
> @tool
> def construct_dict(**kwargs):
>     return kwargs
> ```
> 
> Would you mind sharing your user scenario to help us understand why you want this feature?

```yaml
outputs:
  answer:
    type: string
    is_chat_output: true
    reference: ${reduce_result_tool.output.result}
```
the ouputs part of my dag yaml. the reference must specify one node. but the output of my dag is controlled by input, there me be nodeA's output or nodeB's output.
so i write a reduce_result_tool, the input of reduce_result_tool is nodeA and nodeB's output.  the output is decided by which is not null.

```python
@tool
def reduce_result(result_1: dict = {}, result_2: dict = {}, result_3: dict = {}
                       , result_4: dict = {}, result_5: dict = {}, result_6: dict = {}
                       , result_7: dict = {}, result_8: dict = {}, result_9: dict = {}
                       , result_10: dict = {}
                       ) -> dict:
    """
    收集结果
    """
    if len(result_1) != 0:
        return {"result": result_1}
    if len(result_2) != 0:
        return {"result": result_2}
    if len(result_3) != 0:
        return {"result": result_3}
    if len(result_4) != 0:
        return {"result": result_4}
    if len(result_5) != 0:
        return {"result": result_5}
    if len(result_6) != 0:
        return {"result": result_6}
    if len(result_7) != 0:
        return {"result": result_7}
    if len(result_8) != 0:
        return {"result": result_8}
    if len(result_9) != 0:
        return {"result": result_9}
    if len(result_10) != 0:
        return {"result": result_10}
    # for result in result_list:
    #     if len(result) != 0:
    #         return {"result": result}
    # for value in result_dict.values():
    #     if len(value) != 0:
    #         return {"result": value}
    return {"result": ""}
```
any another solution?

**Comment by thy09** [comment]
What do you think of this?
```
@tool
def reduce_result(**kwargs) -> dict:
    for key, result in kwargs.items():
        if len(result) > 0:
            print("Use result from: ", key)
            return {"result": result}
    return {"result": ""}
```

**Comment by zhangjunqiang** [comment]
> @tool
> def reduce_result(**kwargs) -> dict:
>     for key, result in kwargs.items():
>         if len(result) > 0:
>             print("Use result from: ", key)
>             return {"result": result}
>     return {"result": ""}

got it, thank you for reply~

**Comment by zhangjunqiang** [comment]
> What do you think of this?
> 
> ```
> @tool
> def reduce_result(**kwargs) -> dict:
>     for key, result in kwargs.items():
>         if len(result) > 0:
>             print("Use result from: ", key)
>             return {"result": result}
>     return {"result": ""}
> ```

i am writing a tool package, i wanna know how to write the yaml.
now the yaml like 
```yaml
llmops_pf_ext.tools.reduce_result_tool.reduce_result:
  function: reduce_result
  inputs:
    result_1:
      type:
      - dict
    result_2:
      type:
        - dict
    result_3:
      type:
        - dict
    result_4:
      type:
        - dict
    result_5:
      type:
        - dict
    result_6:
      type:
        - dict
    result_7:
      type:
        - dict
    result_8:
      type:
        - dict
    result_9:
      type:
        - dict
    result_10:
      type:
        - dict
  module: llmops_pf_ext.tools.reduce_result_tool
  name: reduce_result_tool
  description: reduce all result in this node
  type: python

```
any another better solution(the current yaml's inputs is ugly, and cannot process inputs length is bigger than 10).

**Comment by thy09** [comment]
We have an ongoing task to add a hint for `**kwargs`, but we don't have that now.
As a workaround, you can set inputs as `{}`, then put the inputs values in the yaml.

**Comment by zhangjunqiang** [comment]
> We have an ongoing task to add a hint for `**kwargs`, but we don't have that now. As a workaround, you can set inputs as `{}`, then put the inputs values in the yaml.

like this?
```yaml
llmops_pf_ext.tools.reduce_result_tool.reduce_result:
  function: reduce_result
  inputs: {}
  module: llmops_pf_ext.tools.reduce_result_tool
  name: reduce_result_tool
  description: reduce all result in this node
  type: python

```

**Comment by thy09** [comment]
Yes, I think this works. Then you can put the inputs in the yaml like this:
```yaml
- name: reduce
  type: python
  source:
    type: package
    tool: llmops_pf_ext.tools.reduce_result_tool.reduce_result
  inputs:
     result_1: xxx
     result_2: xxx
```
